### PR TITLE
Update 05-styles.md

### PR DESCRIPTION
**Pull request by F-Sampaio**
The style for .tasks > li and .tasks > button are incomplete.

### CODE REVIEW

**Comment by filipenevola** [comment]
Hi @F-Sampaio can you show me how is it looking without your change and after your change? It is looking ok for me.

**Comment by adjiekrazz** [comment]
Just edit your /imports/ui/Task.jsx
add className="task" into <li> tags.

**Comment by shadoath** [comment]
new PW with changed code in #15

**Comment by filipenevola** [comment]
With #15 PR merged, is this PR here still needed?

**Pull request closed without merging**
