### PR TITLE
Update 07-adding-user-accounts.md

### PR DESCRIPTION
**Pull request by zzboncak**
Importing Meteor in `App.jsx` provides helpful autocompletion for the newer user. While it does seem to work without it, it is imported in various other files for this purpose, so it seems best to stay consistent.

### CODE REVIEW

**Review by StorytellerCZ — APPROVED** [review]
Looks good! Should have been there in the first place.

**Comment by StorytellerCZ** [comment]
I have also added it to the source code so that the sample is consistent with what is written. @zzboncak can you please sign the CLA so that we can merge this?

**Comment by zzboncak** [comment]
Yep! Just did.

**Comment by StorytellerCZ** [comment]
Thanks a lot! Merged.

**Pull request merged**
