### PR TITLE
Update Task.jsx to have correct className

### PR DESCRIPTION
**Pull request by shadoath**
New Styling in step 5.2 does not outline this change.

### CODE REVIEW

**Comment by shadoath** [comment]
Bump, can this be merged?

**Comment by filipenevola** [comment]
Hi @shadoath, sorry for the delay here.

Thank you for your PR, we really appreciate it.

Important comment: every step starts from the state of the last one.

So could you change your PR to include your changes on all further steps (step06, 07 ...)? Like
- `src/simple-todos/step06/imports/ui/Task.jsx`
- `src/simple-todos/step07/imports/ui/Task.jsx`
- `src/simple-todos/step08/imports/ui/Task.jsx`
- ...

Otherwise I will need to reject this PR and make this change in a new PR because we can't have steps out of sync.

**Comment by shadoath** [comment]
@filipenevola All steps update to match. Thank you for pointing that out.
Also merged changes from master.

**Comment by filipenevola** [comment]
Hi, the problem was in the instruction and not in the code, we don't have "task" className in the code.

It's fixed here https://github.com/meteor/react-tutorial/commit/39fa511078abe4998ba109386591814dca568d69.

Thank you for your contribution 😉

**Pull request closed without merging**
